# 开发环境，外部用户无法访问，开发人员使用，版本变动很大
spring:
  # 数据源
  datasource:
    # 数据库连接url
    url: jdbc:mysql://127.0.0.1:3306/quick-start?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
    # 默认hikari连接池配置
    hikari:
      # 连接池名称
      pool-name: Retail_HikariCP
      # 最小空闲连接数量
      minimum-idle: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 120000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 测试连接query
      connection-test-query: SELECT 1