# spring
spring:
  # 应用
  application:
    # 名称
    name: ServerBoot
  # mvc
  mvc:
    # 404抛出异常
    throw-exception-if-no-handler-found: true
  # web
  web:
    # 资源
    resources:
      # 映射
      add-mappings: false
  # 数据源
  datasource:
    # url
    url: jdbc:mysql://127.0.0.1:3306/server_boot?serverTimezone=UTC
    # 驱动名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 用户名
    username: root
    # 密码
    password: 123456
    # hikari数据源
    hikari:
      #连接池名称
      pool-name: Retail_HikariCP
      #最小空闲连接数量
      minimum-idle: 10
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 120000
      #连接池最大连接数，默认是10
      maximum-pool-size: 20
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      #配置了这个query则每次拿连接的时候用这个query测试，否则就使用java.sql.Connection的isValid测试  推荐jdbc4不配置。
      connection-test-query: SELECT 1
# mybatis-plus配置
mybatis-plus:
  # 全局配置
  global-config:
    # db配置
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
# 服务
server:
  # 端口
  port: 8888
  # ssl证书
  ssl:
    # 证书路径
    key-store: classpath:codvision.jks
    # 密钥密码
    key-password: Codvision@2020
    # 密钥库密码
    key-store-password: Codvision@2020
    # 证书别名
    key-alias: codvision

