# spring
spring:
  # 应用
  application:
    # 名称
    name: ServerBoot
  # mvc
  mvc:
    # 404抛出异常
    throw-exception-if-no-handler-found: true
  # web
  web:
    # 资源
    resources:
      # 映射
      add-mappings: false
  # 数据源
  datasource:
    # url
    url: jdbc:mysql://127.0.0.1:3306/server_boot?serverTimezone=UTC
    # 驱动名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 用户名
    username: root
    # 密码
    password: 123456
    # hikari数据源
    hikari:
      #连接池名称
      pool-name: Retail_HikariCP
      #最小空闲连接数量
      minimum-idle: 10
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 120000
      #连接池最大连接数，默认是10
      maximum-pool-size: 20
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      #配置了这个query则每次拿连接的时候用这个query测试，否则就使用java.sql.Connection的isValid测试  推荐jdbc4不配置。
      connection-test-query: SELECT 1
  # kafka
  kafka:
    # 服务器
    bootstrap-servers: localhost:9092
    # Kafka提供的序列化和反序列化类
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # 消费组
    consumer:
      properties:
        group.id: codvision
    # 消费监听接口监听的主题不存在时，默认会报错因此要关掉这个
    listener:
      missing-topics-fatal: false
  # redis
  redis:
    # ip地址
    host: 10.0.6.89
    # 端口
    port: 6379
    # 密码
    password: 123456
    # lettuce
    lettuce:
      # 连接池
      pool:
        # 最大连接
        max-active: 8
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
        # 连接等待时间
        max-wait: 100
# mybatis-plus配置
mybatis-plus:
  # 全局配置
  global-config:
    # db配置
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
# 服务
server:
  # 端口
  port: 8888
  # ssl证书
  ssl:
    # 证书路径
    key-store: classpath:codvision.jks
    # 密钥密码
    key-password: Codvision@2020
    # 密钥库密码
    key-store-password: Codvision@2020
    # 证书别名
    key-alias: codvision

# Actuator
management:
  endpoints:
    web:
      exposure:
        # 开放所有endpoints
        include: '*'
        # 关闭
        # exclude: beans
      # 基础路径
      # base-path: /manage
      # path-mapping:
        # health修改成healthcheck
        # health: healthcheck
  endpoint:
    shutdown:
      # 开启/actuator/shutdown
      enabled: true
    beans:
      cache:
        # 不带参数的端点请求会自动进行缓存时间
        time-to-live: 100s
    # server:
    # 修改默认端口
    # port: 10111
    health:
      # 查看详细的应用健康信息
      show-details: always
      # mongo:
        # 禁用某个组件的健康监测
        # enabled: false
      # 禁用所有自动配置的健康指示器
      #defaults:
        # enabled: false
